name: Build (Modern)

on:
  workflow_dispatch:

jobs:
  build-msvc:
    name: Build MSVC ${{ matrix.config.platform }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config:
        - name: x64
          generator: "Visual Studio 17 2022"
          platform: x64
          arch: Win32

        - name: arm64
          generator: "Visual Studio 17 2022"
          platform: ARM64
          arch: ARM64

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake -G "${{ matrix.config.generator }}" -A ${{ matrix.config.arch }} -DCMAKE_BUILD_TYPE=Release -B build -S .

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Create release folder
      run: |
        New-Item -ItemType Directory -Force release | Out-Null

    - name: Copy executable
      run: |
        Copy-Item "build/Release/NextCppShot.exe" release/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nextcppshot-msvc-${{ matrix.config.name }}
        path: ./release/

  build-mingw:
    name: Build MinGW x64
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install MinGW
      run: |
        choco install mingw -y

    - name: Configure
      env:
        PATH: 'C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;C:\Windows\System32;C:\Windows'
      run: |
        cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -B build -S .

    - name: Build
      shell: cmd
      run: |
        cmake --build build --config Release

    - name: Create release folder
      shell: cmd
      run: |
        if not exist release mkdir release
        move build\NextCppShot.exe release\

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nextcppshot-mingw-x64
        path: ./release/
